### ISSUE TITLE
MemoryError when Loading caffe model

### ISSUE THREAD

**Issue by tabsun** [apple2373/chainer_stylenet#1]
After installing all the dependencies, the demo command 
"python style_net.py -g -1 -c kinkaku.jpg -s style.png -d kinkaku"
seems begin to work correctly.
And I got:
Loading caffe model.It takes time...
Then got the error:
—————————————————————————————————————————————
Traceback (most recent call last):
  File "style_net.py", line 134, in <module>
    func = caffe.CaffeFunction('VGG_ILSVRC_19_layers.caffemodel')
  File "/usr/lib/python2.6/site-packages/chainer/functions/caffe/caffe_function.py", line 108, in **init**
    net.MergeFromString(model_file.read())
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/python_message.py", line 841, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/python_message.py", line 874, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/decoder.py", line 633, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/python_message.py", line 874, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/decoder.py", line 633, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/python_message.py", line 874, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/decoder.py", line 220, in DecodePackedField
    value.append(element)
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/containers.py", line 111, in append
    self._values.append(self._type_checker.CheckValue(value))
MemoryError
—————————————————————————————————————————————
And I have observed the memory usage,it's not exhausted. So anyone have the same problem?

**Comment by runfuture** [comment]
It should be your memory of GPU exhausted. Try CPU mode ( -g -1 ).

**Comment by tabsun** [comment]
I am using CPU instead of GPU，you can see this in my command above，but the error is under CPU environment.

**Comment by tabsun** [comment]
OK, it's because of x86_64 and i686 difference. I reinstall the x86_64 system then the error is removed.
