### ISSUE TITLE
arr does not have a suitable array shape for any mode

### ISSUE THREAD

**Issue by alex-chan** [apple2373/chainer_stylenet#3]
<pre/>
 chainer_stylenet-master>  sudo python style_net.py -g -1 -c kinkaku.jpg -s style.png -d kinkaku
Traceback (most recent call last):
  File "style_net.py", line 130, in <module>
    p=readimage(content_image)#read content image
  File "style_net.py", line 62, in readimage
    img = imresize(img,[224, 224])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/misc/pilutil.py", line 411, in imresize
    im = toimage(arr, mode=mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/misc/pilutil.py", line 228, in toimage
    raise ValueError("'arr' does not have a suitable array shape for any mode.")
ValueError: 'arr' does not have a suitable array shape for any mode.
</pre>

**Comment by TheNightIsYoung** [comment]
I have the same problem with you, how did you deal with it ？thanks
